// routes/paymentRoutes.js
import express from 'express';
import Stripe from 'stripe';
import dotenv from 'dotenv';

dotenv.config();

const router = express.Router();
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

// Payment route
router.post('/charge', async (req, res) => {
    const { amount, currency, source, name, email, mobile } = req.body;

    try {
        const charge = await stripe.charges.create({
            amount, // Amount in cents
            currency,
            source, // Token generated by Stripe
            receipt_email: email, // Email for receipt
            description: `Payment from ${name} (${mobile})`, // Description with name and mobile
        });

        res.status(200).json({
            success: true,
            message: 'Payment successful',
            charge,
        });
    } catch (error) {
        console.error('Payment error:', error);
        res.status(500).json({
            success: false,
            message: 'Payment failed',
            error: error.message,
        });
    }
});

export default router;
